version: "3.9"
services:
  

  Departement:
    container_name: departement
    build: ./Departement 
    ports:
      - "3000:3000"  
    environment:
      - MONGODB_URI=mongodb://root:root@mongodb:27017/departement_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/ 

    image: "departementms"
    restart: unless-stopped
    depends_on:
      - Eureka
      - mongodb    

 
  Eureka:
    container_name: eureka
    build: .\Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"   
    image: "eureka"
    
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

    

  Gateway:
    container_name: gatewway
    build: .\API_Gateway_Server
    hostname: gateway
    ports:
      - "8090:8090"   
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    image: "gateway"
    restart: always
    depends_on:
      - Eureka


  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    restart: unless-stopped  

  
  